/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_glimrrenderer_free: (a: number, b: number) => void;
export const glimr_log: (a: number, b: number, c: number, d: number) => void;
export const glimrrenderer_begin_zip_stream: (a: number) => void;
export const glimrrenderer_draw: (a: number, b: number, c: number) => [number, number];
export const glimrrenderer_draw_hover_indicator: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const glimrrenderer_draw_zoomed: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const glimrrenderer_feed_bytes: (a: number, b: number, c: number) => [number, number, number];
export const glimrrenderer_get_image_bytes: (a: number, b: number) => any;
export const glimrrenderer_image_count: (a: number) => number;
export const glimrrenderer_image_file_size: (a: number, b: number) => number;
export const glimrrenderer_image_height: (a: number, b: number) => number;
export const glimrrenderer_image_name: (a: number, b: number) => [number, number];
export const glimrrenderer_image_width: (a: number, b: number) => number;
export const glimrrenderer_is_decoded: (a: number, b: number) => number;
export const glimrrenderer_is_stream_done: (a: number) => number;
export const glimrrenderer_new: (a: any, b: any) => [number, number, number];
export const glimrrenderer_receive_pixels: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const glimrrenderer_watermarked_pixels: (a: number, b: number) => any;
export const xor_decode: (a: number, b: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
